### ISSUE TITLE
Primary CSS font-family falls back to browser default

### ISSUE THREAD

**Issue by acusti** [jspm/jspm.io#10]
The main CSS `font-family` declaration only specifies Myriad Pro:

``` css
      h1, h2, h3, h4, h5, h6, p, li, a {
        font-family: 'Myriad Pro';
        -webkit-font-smoothing: antialiased;
        font-weight: 100;
      }
```

So if the user doesn’t have it installed, it uses the browser default styles and font, which is generally a serif (Times New Roman), and which doesn’t look good in the design of the page. OS X 10.10 and iOS 7 come bundled with [Myriad Set Pro](https://en.wikipedia.org/wiki/Myriad_%28typeface%29#Myriad_Set_Pro), so that’s probably worth including in your stack. And you will want fallback fonts for people who don’t have Myriad. The simplest, safest bet is probably Helvetica, with a final fallback to whatever generic sans-serif.

A separate issue that comes up when I added Myriad Set Pro is that it includes an Ultralight version, which mean that combined with turning off subpixel antialiasing, the text winds up feeble and wispy. If you want a generally lighter look, I would use the regular (400) weight with subpixel-antialiasing disabled, and lighter weight (100 or 200, which are effectively the same) with subpixel-antialiasing reenabled for headings (`h1` through `h4`, because as it stands, `h5` and `h6` are tiny). And I would suggest reenabling subpixel-antialiasing for inline `<code>` elements to (very) subtly differentiate it from the surrounding body text.

I would therefore suggest replacing the above CSS in the HTML with:

``` css
      h1, h2, h3, h4, h5, h6, p, li, a {
        font-family: 'Myriad Pro', 'Myriad Set Pro', Myriad, 'Helvetica Neue', Helvetica, sans-serif;
        -webkit-font-smoothing: antialiased;
        font-weight: 400;
      }
      h1, h2, h3, h4 {
        -webkit-font-smoothing: subpixel-antialiased;
        font-weight: 200;
      }
      code {
        -webkit-font-smoothing: subpixel-antialiased;
      }
```
